### PR TITLE
Update Get-EdgeEnterpriseMSI.ps1

### PR DESCRIPTION
**Pull request by KarlGrindon**
Various improvements made.

Script now handles multiple files (e.g. MacOS Edge files)

Parameter validation

Error handling (replacing write-host -colour red + breaks with throws

Formatting improvements

URI validation

bumped version

Other changes

### CODE REVIEW

**Comment by matbe** [comment]
I have reviewed your changes and great job! Just two questions.
1. Why have you moved the "cmdletbinding" inside the Param statement? What is the difference (I'm just curious)? The documentation shows it to be on the outside?
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_cmdletbindingattribute?view=powershell-5.1
2. If there is a file existing a you select No I would prefer if the script does not throw an error (since it works as designed)
so maybe replace:
`throw "File already exists and user chose not to overwrite"`
with:
`Write-Host "File already exists and user chose not to overwrite, exiting script." -ForegroundColor Red
exit`

**Comment by KarlGrindon** [comment]
You're correct about point 1 - I'll revert that change

As for point 2, I agree - I didn't think about it that way.

I'll make the necessary changes

**Comment by KarlGrindon** [comment]
Changes made

**Comment by matbe** [comment]
Merged now, thanks for your contribution!

**Pull request merged**
